# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'deviceID' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # NOTE: Special release using the NativeCompute integrated Branch SDK
  # Pods for deviceID

  # Podspecs have not yet shipped, so use a local copy
  pod 'BranchNative', :path => '~/github/native/branch-native-ios'
  #pod 'BranchNative'
  pod 'NativeComputeSDK', :path => '~/github/native/nativesdk-podspec'
  #pod 'NativeComputeSDK'

end
